services:

  load-balancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/load-balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: .
    volumes:
      - .:/var/www
    container_name: app1
    hostname: app1
    depends_on:
      - mysql

  app2:
    build: .
    volumes:
      - .:/var/www
    container_name: app2
    hostname: app2
    depends_on:
      - mysql

  app3:
    build: .
    volumes:
      - .:/var/www
    container_name: app3
    hostname: app3
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    ports:
        - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
